### ISSUE TITLE
hi infos

### ISSUE THREAD

**Issue by Exotikcheatt** [donnaskiez/ac#3]
hi is this project safe on the apex legends thanks a lot

**Comment by donnaskiez** [comment]
This isn't a cheat program, it's simply a personal anti cheat project. It isn't mean to be used with games such as Apex Legends as apex already has an anti cheat + in order for you to load it you'd need to sign the driver and even then you won't be able to inject the dll into apex since apex (once again) already has an anti-cheat. I think you are misunderstanding the point of this project.
